---
title: "NIK"
author: "Jose Tamez"
date: "`r Sys.Date()`"
output: 
  html_document: 
    toc: yes
    fig_caption: yes
    number_sections: yes
  word_document: 
    reference_docx: WordStyle_FRESA.docx
    toc: yes
    fig_caption: yes
editor_options:
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(collapse = TRUE, warning = FALSE, message = FALSE,comment = "#>")
```

# NIK

### Loading the libraries

```{r}
library("FRESA.CAD")
library(readxl)
library(igraph)
library(Biobase)
library("breastCancerNKI")

op <- par(no.readonly = TRUE)
pander::panderOptions('digits', 3)
pander::panderOptions('table.split.table', 400)
pander::panderOptions('keep.trailing.zeros',TRUE)

signedrcube <- function(x) { return (sign(x)*(abs(x)^(1/3)))}

```

## The Data


```{r}
data(nki)

nkiDf <- as.data.frame(t(exprs(nki)))
pdata <- pData(nki)
experimentData(nki)

TrainFraction <- 0.8
```

### Cross Validation

```{r results = "asis", warning = FALSE, dpi=600, fig.height= 6.0, fig.width= 8.0}
cvBSWiMSRaw <- randomCV(NIKset,
                "V1",
                fittingFunction= BSWiMS.model,
                classSamplingType = "Pro",
                trainFraction = TrainFraction,
                repetitions = 50,
                loops=1,
)
bpde <- predictionStats_binary(cvBSWiMSRaw$medianTest,"BSWiMS Raw",cex=0.90)
par(op)

```

```{r}
deNIK <- GDSTMDecorrelation(NIKset,Outcome="V1",thr=0.90,verbose = TRUE)
sum(str_detect(colnames(deNIK),"De_"))
sum(str_detect(colnames(deNIK),"Ba_"))

```


```{r}
cvBSWiMSDeCor <- randomCV(NIKset,
                "V1",
                trainSampleSets= cvBSWiMSRaw$trainSamplesSets,
                fittingFunction= filteredFit,
                fitmethod=BSWiMS.model,
                filtermethod=NULL,
                DECOR = TRUE,
                DECOR.control=list(Outcome="V1",thr=0.90),
                loops=1,
)
bpde <- predictionStats_binary(cvBSWiMSDeCor$medianTest,"BSWiMS De",cex=0.90)
par(op)

```

