---
title: "Univariate Options Threshold: Parkinson's"
author: "Jose Tamez"
date: "`r Sys.Date()`"
output: 
  html_document: 
    toc: yes
    fig_caption: yes
    number_sections: yes
  word_document: 
    reference_docx: WordStyle_FRESA.docx
    toc: yes
    fig_caption: yes
editor_options:
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(collapse = TRUE, warning = FALSE, message = FALSE,comment = "#>")
```

# Thermal Covid-19 Univariate

### Loading the libraries

```{r}
library("FRESA.CAD")
library(readxl)
op <- par(no.readonly = TRUE)
pander::panderOptions('digits', 3)
pander::panderOptions('table.split.table', 400)
pander::panderOptions('keep.trailing.zeros',TRUE)
signedlog <- function(x) { return (sign(x)*(abs(log10(abs(1.0e12*x)+1.0)-12.0)))}


```




## The Data

```{r}

pd_speech_features <- as.data.frame(read_excel("~/GitHub/FCA/Data/pd_speech_features.xlsx",sheet = "pd_speech_features", range = "A2:ACB758"))




```

### The Average of the Three Repetitions

Each subject had three repeated observations. Here I'll use the average of the three experiments per subject.

```{r results = "asis", warning = FALSE, dpi=600, fig.height= 6.0, fig.width= 8.0}
rep1Parkison <- subset(pd_speech_features,RID==1)
rownames(rep1Parkison) <- rep1Parkison$id
rep1Parkison$id <- NULL
rep1Parkison$RID <- NULL
rep1Parkison[,1:ncol(rep1Parkison)] <- sapply(rep1Parkison,as.numeric)

rep2Parkison <- subset(pd_speech_features,RID==2)
rownames(rep2Parkison) <- rep2Parkison$id
rep2Parkison$id <- NULL
rep2Parkison$RID <- NULL
rep2Parkison[,1:ncol(rep2Parkison)] <- sapply(rep2Parkison,as.numeric)

rep3Parkison <- subset(pd_speech_features,RID==3)
rownames(rep3Parkison) <- rep3Parkison$id
rep3Parkison$id <- NULL
rep3Parkison$RID <- NULL
rep3Parkison[,1:ncol(rep3Parkison)] <- sapply(rep3Parkison,as.numeric)

whof <- !(colnames(rep1Parkison) %in% c("gender","class"));
avgParkison <- rep1Parkison;
avgParkison[,whof] <- (rep1Parkison[,whof] + rep2Parkison[,whof] + rep3Parkison[,whof])/3
## I apply the log transform to the data
##avgParkison[,whof] <- signedlog(avgParkison[,whof])
avgParkison[,whof] <- FRESAScale(avgParkison[,whof],method="OrderLogit")$scaledData
pander::pander(table(avgParkison$class))

```

#### Standarize the names for the reporting

```{r results = "asis"}
dataframe <- avgParkison
outcome <- "class"
n_topfeatures <- 5

```



```{r results = "asis"}
pander::pander(c(rows=nrow(dataframe),col=ncol(dataframe)-1))
pander::pander(table(dataframe[,outcome]))

varlist <- colnames(dataframe)
varlist <- varlist[varlist != outcome]
varlist <- as.data.frame(cbind(name=varlist,desc=varlist))

```



## Threshold Analysis

```{r results = "asis", warning = FALSE, dpi=600, fig.height= 5.0, fig.width= 7.0}

toplist <- c(1:n_topfeatures)

univariate_columns <- c("caseMean","caseStd","controlMean","controlStd","cohortKSP","ROCAUC","WilcoxRes.p","FRes.p")

univar <- uniRankVar(varlist,
	           paste(outcome,"~1"),
	           outcome,
	           dataframe,
	           categorizationType = "Raw",
	           type = "LOGIT",
	           rankingTest = "AUC",
	            uniType = "Binary")

topnames <- c(outcome,univar$orderframe[toplist,"Name"])
topfivelm <- glm(paste(outcome,"~."),dataframe[,topnames],family="binomial")
print(summary(topfivelm))
bpraw <- predictionStats_binary(cbind(dataframe[,outcome],predict(topfivelm,dataframe)),"Logit RAW",cex=0.90)
par(op)

  accs <-bpraw$accc
  aucs <-bpraw$aucs
  bers <-bpraw$berror

optionNames <- character();
thrval <- 0.95
for (thrval in c(0.95,0.90,0.85,0.80,0.75,0.70,0.65,0.60,0.55,0.50))
{
  DEdataframe <- GDSTMDecorrelation(dataframe,Outcome=outcome,thr=thrval)
  tvarlist <-  colnames(DEdataframe)[colnames(DEdataframe) != "class"];
  tvarlist <- as.data.frame(cbind(name=tvarlist,desc=tvarlist))

  univar <- uniRankVar(tvarlist,
	           paste(outcome,"~1"),
	           outcome,
	           DEdataframe,
	           categorizationType = "Raw",
	           type = "LOGIT",
	           rankingTest = "AUC",
	            uniType = "Binary")

  nameopt <- paste("OD_At_",thrval,sep="");
  optionNames <- c(optionNames,nameopt)
  topnames <- c(outcome,univar$orderframe[toplist,"Name"])

  topfivelm <- glm(paste(outcome,"~."),DEdataframe[,topnames],family="binomial")
  print(summary(topfivelm))
  
  bppred <- predictionStats_binary(cbind(dataframe[,outcome],predict(topfivelm,DEdataframe)),nameopt,cex=0.90)

  aucs <- rbind(aucs,bppred$aucs)
  bers <- rbind(bers,bppred$berror)
  accs <- rbind(accs,bppred$accc)

}

rownames(aucs) <- c("raw",optionNames);
rownames(bers) <- c("raw",optionNames);
rownames(accs) <- c("raw",optionNames);
par(op)

```


### Error plots
```{r results = "asis", warning = FALSE, dpi=600, fig.height= 5.0, fig.width= 7.0}

  bpAUC <- barPlotCiError(as.matrix(aucs),
                          metricname = "ROC AUC: Top",
                          thesets = "AUC",
                          themethod = rownames(aucs),
                          main = "ROC AUC",
                          offsets = c(0.5,1),
                          scoreDirection = ">",
                          ho=0.5,
                          args.legend = list(bg = "white",x="bottomright",inset=c(0.0,0),cex=0.6),
                          col = terrain.colors(nrow(aucs))
                          )

pander::pander(as.data.frame(bpAUC$ciTable))

  bpACC <- barPlotCiError(as.matrix(accs),
                          metricname = "Accuracy: Top",
                          thesets = "Accuracy",
                          themethod = rownames(accs),
                          main = "Accuracy",
                          offsets = c(0.5,1),
                          scoreDirection = ">",
                          ho=0.5,
                          args.legend = list(bg = "white",x="bottomright",inset=c(0.0,0),cex=0.6),
                          col = terrain.colors(nrow(aucs))
                          )
  
  pander::pander(as.data.frame(bpACC$ciTable))

  bpBer <- barPlotCiError(as.matrix(bers),
                          metricname = "BER: Top",
                          thesets = "BER",
                          themethod = rownames(bers),
                          main = "BER",
                          offsets = c(0.5,1),
                          scoreDirection = "<",
                          ho=0.5,
                          args.legend = list(bg = "white",x="topleft",inset=c(0.0,0),cex=0.6),
                          col = terrain.colors(nrow(aucs))
                          )
  
    pander::pander(as.data.frame(bpBer$ciTable))


```


