---
title: "Univariate: TADPOLE"
author: "Jose Tamez"
date: "`r Sys.Date()`"
output: 
  html_document: 
    toc: yes
    fig_caption: yes
    number_sections: yes
  word_document: 
    reference_docx: WordStyle_FRESA.docx
    toc: yes
    fig_caption: yes
editor_options:
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(collapse = TRUE, warning = FALSE, message = FALSE,comment = "#>")
```

# TADPOLE Univariate

### Loading the libraries

```{r}
library("FRESA.CAD")
library(readxl)
op <- par(no.readonly = TRUE)
pander::panderOptions('digits', 3)
pander::panderOptions('table.split.table', 400)
pander::panderOptions('keep.trailing.zeros',TRUE)

```



## The Data


## The data set

```{r}
TADPOLE_D1_D2 <- read.csv("~/GitHub/FCA/Data/TADPOLE/TADPOLE_D1_D2.csv")
TADPOLE_D1_D2_Dict <- read.csv("~/GitHub/FCA/Data/TADPOLE/TADPOLE_D1_D2_Dict.csv")
TADPOLE_D1_D2_Dict_LR <- as.data.frame(read_excel("~/GitHub/FCA/Data/TADPOLE/TADPOLE_D1_D2_Dict_LR.xlsx",sheet = "LeftRightFeatures"))


rownames(TADPOLE_D1_D2_Dict) <- TADPOLE_D1_D2_Dict$FLDNAME

```

## Conditioning the data

```{r results = "asis", warning = FALSE, dpi=600, fig.height= 6.0, fig.width= 8.0}

# mm3 to mm
isVolume <- c("Ventricles","Hippocampus","WholeBrain","Entorhinal","Fusiform","MidTemp","ICV",
              TADPOLE_D1_D2_Dict$FLDNAME[str_detect(TADPOLE_D1_D2_Dict$TEXT,"Volume")]
              )


#TADPOLE_D1_D2[,isVolume] <- apply(TADPOLE_D1_D2[,isVolume],2,'^',(1/3))
TADPOLE_D1_D2[,isVolume] <- TADPOLE_D1_D2[,isVolume]^(1/3)

# mm2 to mm
isArea <- TADPOLE_D1_D2_Dict$FLDNAME[str_detect(TADPOLE_D1_D2_Dict$TEXT,"Area")]
TADPOLE_D1_D2[,isArea] <- sqrt(TADPOLE_D1_D2[,isArea])

# Get only cross sectional measurements
FreeSurfersetCross <- str_detect(colnames(TADPOLE_D1_D2),"UCSFFSX")

# The subset of baseline measurements
baselineTadpole <- subset(TADPOLE_D1_D2,VISCODE=="bl")
table(baselineTadpole$DX)

rownames(baselineTadpole) <- baselineTadpole$PTID


validBaselineTadpole <- cbind(DX=baselineTadpole$DX,
                                 AGE=baselineTadpole$AGE,
                                 Gender=1*(baselineTadpole$PTGENDER=="Female"),
                                 ADAS11=baselineTadpole$ADAS11,
                                 ADAS13=baselineTadpole$ADAS13,
                                 MMSE=baselineTadpole$MMSE,
                                 RAVLT_immediate=baselineTadpole$RAVLT_immediate,
                                 RAVLT_learning=baselineTadpole$RAVLT_learning,
                                 RAVLT_forgetting=baselineTadpole$RAVLT_forgetting,
                                 RAVLT_perc_forgetting=baselineTadpole$RAVLT_perc_forgetting,
                                 FAQ=baselineTadpole$FAQ,
                                 Ventricles=baselineTadpole$Ventricles,
                                 Hippocampus=baselineTadpole$Hippocampus,
                                 WholeBrain=baselineTadpole$WholeBrain,
                                 Entorhinal=baselineTadpole$Entorhinal,
                                 Fusiform=baselineTadpole$Fusiform,
                                 MidTemp=baselineTadpole$MidTemp,
                                 ICV=baselineTadpole$ICV,
                                 baselineTadpole[,FreeSurfersetCross])


LeftFields <- TADPOLE_D1_D2_Dict_LR$LFN
names(LeftFields) <- LeftFields
LeftFields <- LeftFields[LeftFields %in% colnames(validBaselineTadpole)]
RightFields <- TADPOLE_D1_D2_Dict_LR$RFN
names(RightFields) <- RightFields
RightFields <- RightFields[RightFields %in% colnames(validBaselineTadpole)]

## Normalize to ICV
validBaselineTadpole$Ventricles=validBaselineTadpole$Ventricles/validBaselineTadpole$ICV
validBaselineTadpole$Hippocampus=validBaselineTadpole$Hippocampus/validBaselineTadpole$ICV
validBaselineTadpole$WholeBrain=validBaselineTadpole$WholeBrain/validBaselineTadpole$ICV
validBaselineTadpole$Entorhinal=validBaselineTadpole$Entorhinal/validBaselineTadpole$ICV
validBaselineTadpole$Fusiform=validBaselineTadpole$Fusiform/validBaselineTadpole$ICV
validBaselineTadpole$MidTemp=validBaselineTadpole$MidTemp/validBaselineTadpole$ICV

leftData <- validBaselineTadpole[,LeftFields]
RightData <- validBaselineTadpole[,RightFields]
#leftData <- validBaselineTadpole[,LeftFields]/validBaselineTadpole$ICV
#RightData <- validBaselineTadpole[,RightFields]/validBaselineTadpole$ICV

## get mean and relative difference 
meanLeftRight <- (leftData + RightData)/2
difLeftRight <- abs(leftData - RightData)

minLeftRight <- pmin(leftData,RightData)
maxLeftRight <- pmax(leftData,RightData)

reldifLeftRight <- difLeftRight/meanLeftRight
#minreldifLeftRight <- difLeftRight/minLeftRight
#maxreldifLeftRight <- difLeftRight/maxLeftRight
maxMinRatio <- minLeftRight/maxLeftRight


colnames(minLeftRight) <- paste("Min",colnames(minLeftRight),sep="_")
colnames(maxLeftRight) <- paste("Max",colnames(maxLeftRight),sep="_")
colnames(meanLeftRight) <- paste("M",colnames(meanLeftRight),sep="_")
colnames(difLeftRight) <- paste("D",colnames(difLeftRight),sep="_")
colnames(reldifLeftRight) <- paste("RD",colnames(reldifLeftRight),sep="_")
colnames(maxMinRatio) <- paste("mMR",colnames(maxMinRatio),sep="_")
#colnames(minreldifLeftRight) <- paste("miMR",colnames(minreldifLeftRight),sep="_")
#colnames(maxreldifLeftRight) <- paste("maMR",colnames(maxreldifLeftRight),sep="_")

#hist(maxMinRatio$mMR_ST32TA_UCSFFSX_11_02_15_UCSFFSX51_08_01_16)
#hist(1.0/maxMinRatio$mMR_ST32TA_UCSFFSX_11_02_15_UCSFFSX51_08_01_16)
#hist(log(1.0e6/maxMinRatio$mMR_ST32TA_UCSFFSX_11_02_15_UCSFFSX51_08_01_16+1))

#hist(reldifLeftRight$RD_ST32TA_UCSFFSX_11_02_15_UCSFFSX51_08_01_16)
#hist(1.0/reldifLeftRight$RD_ST32TA_UCSFFSX_11_02_15_UCSFFSX51_08_01_16)
#hist(log(1.0e6/reldifLeftRight$RD_ST32TA_UCSFFSX_11_02_15_UCSFFSX51_08_01_16+1))


meanLeftRight <- meanLeftRight/validBaselineTadpole$ICV
minLeftRight <- minLeftRight/validBaselineTadpole$ICV
maxLeftRight <- maxLeftRight/validBaselineTadpole$ICV
#difLeftRight <- log10(1.0e6*difLeftRight + 1.0)
#reldifLeftRight <- log10(1.0e6/(1.0e-6+reldifLeftRight) + 1.0)
#maxMinRatio <- log10(1.0e6/(1.0e-6+maxMinRatio) + 1.0)
#minreldifLeftRight <- log10(1.0e6/(1.0e-6+minreldifLeftRight) + 1.0)
#maxreldifLeftRight <- log10(1.0e6/(1.0e-6+maxreldifLeftRight) + 1.0)

validBaselineTadpole <- validBaselineTadpole[,!(colnames(validBaselineTadpole) %in% 
                                               c(LeftFields,RightFields))]
#validBaselineTadpole <- cbind(validBaselineTadpole,meanLeftRight,reldifLeftRight)
#validBaselineTadpole <- cbind(validBaselineTadpole,meanLeftRight,difLeftRight)

validBaselineTadpole <- cbind(validBaselineTadpole,
                              meanLeftRight,
                              difLeftRight,
#                              maxLeftRight,
#                              minLeftRight,
                              reldifLeftRight,
                              maxMinRatio
#                              minreldifLeftRight,
#                              maxreldifLeftRight
                              )

## Remove columns with too many NA more than %15 of NA
nacount <- apply(is.na(validBaselineTadpole),2,sum)/nrow(validBaselineTadpole) < 0.15
diagnose <- validBaselineTadpole$DX
pander::pander(table(diagnose))
validBaselineTadpole <- validBaselineTadpole[,nacount]
## Remove character columns
ischar <- sapply(validBaselineTadpole,class) == "character"
validBaselineTadpole <- validBaselineTadpole[,!ischar]
## Place back diagnose
validBaselineTadpole$DX <- diagnose


validBaselineTadpole <- validBaselineTadpole[complete.cases(validBaselineTadpole),]
ischar <- sapply(validBaselineTadpole,class) == "character"
validBaselineTadpole[,!ischar] <- sapply(validBaselineTadpole[,!ischar],as.numeric)

colnames(validBaselineTadpole) <- str_remove_all(colnames(validBaselineTadpole),"_UCSFFSX_11_02_15_UCSFFSX51_08_01_16")
colnames(validBaselineTadpole) <- str_replace_all(colnames(validBaselineTadpole)," ","_")
validBaselineTadpole$LONISID <- NULL
validBaselineTadpole$IMAGEUID <- NULL
validBaselineTadpole$LONIUID <- NULL

diagnose <- as.character(validBaselineTadpole$DX)
validBaselineTadpole$DX <- diagnose
pander::pander(table(validBaselineTadpole$DX))


validDX <- c("NL","MCI","Dementia")

validBaselineTadpole <- validBaselineTadpole[validBaselineTadpole$DX %in% validDX,]
validBaselineTadpole$DX <- as.factor(validBaselineTadpole$DX)
pander::pander(table(validBaselineTadpole$DX))

TADPOLECrossMRI <- subset(validBaselineTadpole,DX == "Dementia" | DX == "MCI")
table(TADPOLECrossMRI$DX)

TADPOLECrossMRI$DX <- 1*(as.character(TADPOLECrossMRI$DX) == "Dementia")
table(TADPOLECrossMRI$DX)
TADPOLECrossMRI$ADAS13 <- NULL
TADPOLECrossMRI$ADAS11 <- NULL
TADPOLECrossMRI$MMSE <- NULL
TADPOLECrossMRI$RAVLT_immediate <- NULL
TADPOLECrossMRI$RAVLT_learning <- NULL
TADPOLECrossMRI$RAVLT_perc_forgetting <- NULL
TADPOLECrossMRI$RAVLT_forgetting <- NULL
TADPOLECrossMRI$FAQ <- NULL


```



#### Standarize the names for the reporting

```{r results = "asis"}
dataframe <- TADPOLECrossMRI
outcome <- "DX"

```

### Data set info

```{r results = "asis"}
pander::pander(c(rows=nrow(dataframe),col=ncol(dataframe)-1))
pander::pander(table(dataframe[,outcome]))

varlist <- colnames(dataframe)
varlist <- varlist[varlist != outcome]
varlist <- as.data.frame(cbind(name=varlist,desc=varlist))

```


## Univariate

```{r results = "asis"}

univariate_columns <- c("caseMean","caseStd","controlMean","controlStd","cohortKSP","ROCAUC","WilcoxRes.p","FRes.p")
univar <- uniRankVar(varlist,
	           paste(outcome,"~1"),
	           outcome,
	           dataframe,
	           categorizationType = "Raw",
	           type = "LOGIT",
	           rankingTest = "AUC",
	            cateGroups = c(0.1, 0.9),
	            raw.dataFrame = NULL,
	            description = ".",
	            uniType = "Binary")

pander::pander(univar$orderframe[1:60,univariate_columns])

topfiveOrg <- rownames(univar$orderframe[1:5,])


```

## Decorrelation Analysis

```{r results = "asis"}
DEdataframe <- GDSTMDecorrelation(dataframe,Outcome=outcome,thr=0.80,verbose = TRUE,skipRelaxed=FALSE)



demat <- attr(DEdataframe,"GDSTM")

pander::pander(c(Cols=ncol(demat),Rows=nrow(demat)))
totFe <- ncol(DEdataframe)-1
totBa <- sum(str_detect(colnames(DEdataframe),"Ba_"))
totDe <- sum(str_detect(colnames(DEdataframe),"De_"))
toUnmat <- sum(apply(demat!=0,2,sum)==1)
unaltered <- totFe - ncol(demat) + toUnmat
pander::pander(c(Features=totFe,totBa=totBa,totDe=totDe,unaltered=totFe-totBa-totDe,totuna=unaltered))
pander::pander(c(Decorrleated_Fraction=sum(str_detect(colnames(DEdataframe),"De_"))/(ncol(DEdataframe)-1)))
pander::pander(c(Base_Fraction=sum(str_detect(colnames(DEdataframe),"Ba_"))/(ncol(DEdataframe)-1)))

pander::pander(c(Unaltered_Fraction=unaltered/totFe))
pander::pander(c(sparcity=(totFe-ncol(demat)+sum(abs(demat)!=0))/totFe/totFe))

varlistDe <-  colnames(demat)[apply(demat!=0,2,sum)>1];
varlistDe <- as.data.frame(cbind(name=varlistDe,desc=varlistDe))


```


### The heat maps.

```{r results = "asis", warning = FALSE, dpi=300, fig.height= 5.0, fig.width= 7.0}
par(cex=0.6,cex.main=0.85,cex.axis=0.7)
cormat <- cor(dataframe[,rownames(demat)],method="spearman")
cormat[is.na(cormat)] <- 0
gplots::heatmap.2(abs(cormat),
                  trace = "none",
#                  scale = "row",
                  mar = c(5,5),
                  col=rev(heat.colors(5)),
                  main = "Spearman Correlation Original",
                  cexRow = 0.35,
                  cexCol = 0.35,
                  key.title=NA,
                  key.xlab="Spearman Correlation",
                  xlab="Feature", ylab="Feature")


cormat <- cor(DEdataframe[,colnames(demat)],method="spearman")
cormat[is.na(cormat)] <- 0
gplots::heatmap.2(abs(cormat),
                  trace = "none",
#                  scale = "none",
                  mar = c(5,5),
                  col=rev(heat.colors(5)),
                  main = "Spearman Correlation: After GDSTM",
                  cexRow = 0.35,
                  cexCol = 0.35,
                  key.title=NA,
                  key.xlab="Spearman Correlation",
                  xlab="Feature", ylab="Feature")

par(op)
```


## Univariate Decorrelated

```{r results = "asis"}

univarDe <- uniRankVar(varlistDe,
              paste(outcome,"~1"),
	            outcome,
              DEdataframe,
	            categorizationType = "Raw",
	            type = "LOGIT",
	            rankingTest = "AUC",
	            cateGroups = c(0.1, 0.9),
	            raw.dataFrame = NULL,
	            description = ".",
	            uniType = "Binary")

pander::pander(univarDe$orderframe[1:20,univariate_columns])

```

### Comparing Decorrelation vs Original

```{r results = "asis"}
pthr <- 0.20/(ncol(dataframe)-1)

topDecorNames <- rownames(univarDe$orderframe[univarDe$orderframe$FRes.p<pthr,])
topDecorNames <- unique(c(topDecorNames,rownames(univarDe$orderframe[1:5,])))

dc <- getDerivedCoefficients(DEdataframe)
### 2a Get only the ones that in the top features
deNames_in_dc <- topDecorNames[topDecorNames %in% names(dc)]
selectedlist <- dc[deNames_in_dc]
theDeFormulas <- selectedlist
```


## CV ROC Analysis

```{r results = "asis", warning = FALSE, dpi=600, fig.height= 4.0, fig.width= 8.0}
par(op)
par(mfrow=c(1,2),cex=0.9)
fraction <-0.80
repetitions <- 100

fcout <- round(fraction*nrow(dataframe)/15+1.0)
pander::pander(c(NumberofFeatures=fcout))

cvRaw <- randomCV(dataframe,
                outcome,
                fittingFunction= filteredFit,
                classSamplingType = "Pro",
                trainFraction = fraction,
                repetitions = repetitions,
                fitmethod=  glm,
                filtermethod=mRMR.classic_FRESA,
                filtermethod.control=list(feature_count= fcout),
                family="binomial"
)
bpraw <- predictionStats_binary(cvRaw$medianTest,"RAW",cex=0.75)


pander::pander(bpraw$CM.analysis$tab)
pander::pander(bpraw$accc)
pander::pander(bpraw$aucs)
pander::pander(bpraw$berror)

cvDe <- randomCV(DEdataframe,
                outcome,
                fittingFunction= filteredFit,
                trainSampleSets= cvRaw$trainSamplesSets,
                fitmethod=  glm,
                filtermethod=mRMR.classic_FRESA,
                filtermethod.control=list(feature_count= fcout),
                family="binomial"
)
bpDecor <- predictionStats_binary(cvDe$medianTest,"Decorrelated",cex=0.75)

par(op)

pander::pander(bpDecor$CM.analysis$tab)
pander::pander(bpDecor$accc)
pander::pander(bpDecor$aucs)
pander::pander(bpDecor$berror)

### Here we compute the probability that the outcome-driven decorrelation ROC is superior to the RAW ROC. 
pander::pander(roc.test(bpDecor$ROC.analysis$roc.predictor,bpraw$ROC.analysis$roc.predictor,alternative = "greater"))


```

## Feature Frequency Plots
```{r results = "asis", warning = FALSE, dpi=300, fig.height= 6.0, fig.width= 6.0}
par(mfrow=c(2,1),cex=0.9,cex.axis=0.8)

rawtopf <- cvRaw$featureFrequency/repetitions
crawtopf <- rawtopf

if (length(rawtopf) > 40)
{
  rawtopf <- rawtopf[1:40]
}
barplot(100*rawtopf,las=2,main="Raw Features",ylim=c(0,100.0),cex.names = 0.5,cex.axis = 0.5,ylab="Sel. %")

detopf <- cvDe$featureFrequency/repetitions
cdetopf <- detopf
names(cdetopf) <- str_remove_all(names(cdetopf),"Ba_")
names(cdetopf) <- str_remove_all(names(cdetopf),"De_")
if (length(detopf) > 40)
{
  detopf <- detopf[1:40]
}

barplot(100*detopf,las=2,main="Decorrelated Features",ylim=c(0,100.0),cex.names = 0.5,cex.axis = 0.5,ylab="Sel. %")

par(op)



```



### Final Table

```{r results = "asis"}
unlistdecorr <- selectedlist
names(unlistdecorr) <- NULL
unlistdecorr <- unique(names(unlist(unlistdecorr)))

finalTableDe <- univarDe$orderframe[deNames_in_dc,univariate_columns]

finalTableOr <- univar$orderframe[unique(c(topfiveOrg,unlistdecorr,names(crawtopf)[1:2],names(cdetopf)[1:2])),univariate_columns]

finalTable <- rbind(finalTableOr,finalTableDe)

deFromula <- character(length(theDeFormulas))
names(deFromula) <- names(theDeFormulas)

for (dx in names(deFromula))
{
  coef <- theDeFormulas[[dx]]
  cname <- names(theDeFormulas[[dx]])
  names(cname) <- cname
  for (cf in names(coef))
  {
    if (cf != dx)
    {
      if (coef[cf]>0)
      {
        deFromula[dx] <- paste(deFromula[dx],
                               sprintf("+ %5.3f*%s",coef[cf],cname[cf]))
      }
      else
      {
        deFromula[dx] <- paste(deFromula[dx],
                               sprintf("%5.3f*%s",coef[cf],cname[cf]))
      }
    }
  }
}
orgnamez <- rownames(finalTable)
orgnamez <- str_remove_all(orgnamez,"Ba_")
orgnamez <- str_remove_all(orgnamez,"De_")
finalTable$uAUC <- univar$orderframe[orgnamez,"ROCAUC"]
finalTable$raw_Freq <- crawtopf[orgnamez]
finalTable$de_Freq <- cdetopf[orgnamez]
finalTable$DecorFormula <- deFromula[rownames(finalTable)]
finalTable <- finalTable[order(-finalTable$ROCAUC),]

pander::pander(finalTable)
```


